AWSTemplateFormatVersion: 2010-09-09
Resources:
  CrossAccount:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS: 
                - arn:aws:iam::688715217363:role/S3-Copy-Maxmind-LambdaExecutionRole-180F8LIWCJ4FN

              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'

      Path: /

  S3CopyPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub mypolicy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          -
            Effect: Allow
            Action:
              - s3:ListBucket
              - s3:GetObject
            Resource:
              - arn:aws:s3:::application
              - arn:aws:s3:::application/*
          -
            Effect: Allow
            Action:
              - s3:ListBucket
              - s3:PutObject
              - s3:PutObjectAcl
            Resource:
              - arn:aws:s3:::cdosms-prd
              - arn:aws:s3:::dcdosms-prd/warehouse/
      Roles:
        -
          !Ref CrossAccount
