AWSTemplateFormatVersion: 2010-09-09

Resources:  
 SampleBucketPolicy: 
  Type: AWS::S3::BucketPolicy
  Properties: 
    Bucket: <provide source bucket name>
    PolicyDocument: 
      Statement: 
        - 
          Action: 
            - "s3:GetObject"
          Effect: "Allow"
          Resource: 
            Fn::Join: 
              - ""
              - 
                - "arn:aws:s3:::"
                - <provide source bucket name>
                - "/*"
          Principal: 
            AWS:
              - arn:aws:iam::688715217363:role/S3Access-CrossAccount-*
