AWSTemplateFormatVersion: 2010-09-09
Resources:

  S3COPY:
    Type: 'AWS::Lambda::Function'
    Properties:
      Code:
        S3Bucket: <s3 bucket that holds the lambda code>
        S3Key: <lambda code zip file name>
      Description: Lambda function to copy files from an S3 bucket to another S3 bucket
      FunctionName: s3-copy
      Handler: s3_copy.handler
      Role: !GetAtt 
        - LambdaExecutionRole
        - Arn
      Runtime: python3.6

  LambdaExecutionRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'

      Path: /

  S3CopyPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub s3_copy_policy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          -
            Effect: Allow
            Action:
              - sts:AssumeRole
            Resource:
              - <arn of role used in destination account to copy files>
          
      Roles:
        -
          !Ref LambdaExecutionRole
  BucketPolicy: 
   Type: AWS::S3::BucketPolicy
   Properties: 
    Bucket: source-000
    PolicyDocument: 
      Statement: 
        - 
          Action: 
            - "s3:GetObject"
          Effect: "Allow"
          Resource: 
            Fn::Join: 
              - ""
              - 
                - "arn:aws:s3:::"
                - source-000
                - "/*"
          Principal: 
            AWS:
              - <arn of role used in destination account>
